"""Migración inicial

Revision ID: 6395896d139b
Revises: 
Create Date: 2024-11-02 22:02:24.809531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6395896d139b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('alerta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('alerta_id')
    )
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asistencias_aula_id'), ['aula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asistencias_fecha_asistencia'), ['fecha_asistencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_asistencias_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['docente_id'], ['user_id'])

    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_puntos'), ['puntos'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_puntos'))

    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('docente_id')

    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asistencias_user_id'))
        batch_op.drop_index(batch_op.f('ix_asistencias_fecha_asistencia'))
        batch_op.drop_index(batch_op.f('ix_asistencias_aula_id'))

    op.drop_table('alertas')
    # ### end Alembic commands ###
