"""Añadiendo seguridad

Revision ID: 9cee9896acc1
Revises: aca762487638
Create Date: 2024-11-08 22:54:43.839569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cee9896acc1'
down_revision = 'aca762487638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_revocados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens_revocados')
    # ### end Alembic commands ###
