"""Migración inicial después de eliminar codigo_qr

Revision ID: fbe9257d9e4c
Revises: 
Create Date: 2024-11-04 16:20:48.419432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe9257d9e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesionesqr', schema=None) as batch_op:
        batch_op.alter_column('docente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesionesqr', schema=None) as batch_op:
        batch_op.alter_column('docente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
